version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    networks:
      - another-network
    environment:
      - MYSQL_ROOT_PASSWORD=igdefault
      - MYSQL_DATABASE=StudentMyBatis
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test@1234
    ports:
      - 3607:3606
    volumes:
      - "./createTable.sql:/docker-entrypoint-initdb.d/1.sql"


  mongodb-standalone:
    image: mongo:latest
    networks:
      - another-network
    container_name: "mongodb-standalone"
    ports:
      - 27017:27017


  springboot-docker-container:
    image: springboot-docker-container:1.0
    networks:
      - another-network
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
      - mongodb-standalone
    links:
      - mysql-standalone
      - mongodb-standalone

networks:
  another-network: